cognitedata/indsl

.github/workflows/code-quality.yaml
Unit tests are currently not uploaded correctly. They are always reported as 0 tests. 
This makes the workflow halt randomly needing to kick the build with an empty commit etc. Wasting CI runs and developer time.
Running all existing tests
Before this PR:
After this PR:
=> fix: Fix unit test publish

docs-source/source/contribute.rst
Update contrib. guidelines in docs after InDSL was open sourced.
Docs said that InDSL is closed source, which is no longer true. Fixed.
=> fix: Update note about availability after open sourcing

.github/CODEOWNERS
We cannot specify a pattern more than once, so teams with the same pattern must be on the same line as the last matching pattern will take precedence.
=> chore: fix code owners file

CHANGELOG.md, pyproject.toml
Bumping indsl version and preparing for a new release
=> chore: Bump version to 8.3.0

.github/workflows/push-locize.yaml, translations/create_translation_json.py
The JSON file being created with the information from the docstrings in indsl needs to be pushed to Locize, and so a github actions script is made to do so.
[Ticket](https://cognitedata.atlassian.net/jira/software/c/projects/AH/boards/838?assignee=603804315ddf020069cf1eda&selectedIssue=AH-2618)
=> feat: github actions script to push json to locize

CHANGELOG.md, bump_library.sh, pyproject.toml
Bumping version in order to get access to the key-value script inside calculation backend
=> chore: Bump version

translations/create_translation_json.py
Docstring in locize should be in markdown format
=> fix: generation of parameter name should be formatted

indsl/signals/generator.py, indsl/ts_utils/utility_functions.py
REMOVE function has a bug in  RANGE_FROM and RANGE_TO  DESCRIPTION as both are the same.
SINE_WAVE has a bug in END_DATE and START_DATE DESCRIPTION as they are mixed.
[Ticket](https://cognitedata.atlassian.net/browse/AH-2938?atlOrigin=eyJpIjoiOTg5ZDQ3MjVlNzk5NGIyZWE3OTkwMmU4MjY2MmJhZjQiLCJwIjoiaiJ9)
=> fix: change  descriptions of arguments

CHANGELOG.md, pyproject.toml
Releasing new indsl function
New function was implemented
=> chore(bump): version 8.3.3 → 8.4.0

PUBLISHING.md, TRANSLATIONS.md
=> docs: updating translation docs

poetry.lock, pyproject.toml
After updating Scipy, none of the PRs are able to pass CI tests. 
Downgrading scipy. Version 1.13.0 is not able to pass CI/CD due to the failing parallelism while executing github actions. Waiting for the upgraded version. 
CI tests
=> chore: dependency update

.github/workflows/code-quality.yaml
codecov stops  PRs from being merged. This is a wrong behaviour for an open sourced repo where cloned repo does not have access to our codecov
=> chore: codecov failure [AH-3195]

.github/workflows/code-quality.yaml, .pre-commit-config.yaml
Continue on codecov updates
Failing code coverage should not stop from merging PRa
=> chore: continue on error codecov [AH-3195]

.pre-commit-config.yaml, indsl/oil_and_gas/live_fluid_properties.py, pyproject.toml
Updating ruff to the new version
=> chore: updating ruff

indsl/smooth/butterworth.py, indsl/ts_utils/utility_functions.py, tests/smooth/test_smoothers.py, tests/ts_utils/test_utility_functions.py
In cases when user provides a wrong data indsl UserValueError should be return to the user.
=> fix: adding checks for the user input in order to avoid ValueError

indsl/sustainability/co2_emissions_calculations.py
Though several unit systems could be used, I think adding "example" units helps the user understand the calculations.
What do you think @evertoncolling?
=> fix: Add example units to guide users

docs-source/source/contribute.rst
The documentation describing the use of brackets for units in docstrings must be clearer to avoid inconsistencies
in the units.
[Ticket](https://cognitedata.atlassian.net/browse/AH-1040?atlOrigin=eyJpIjoiODEwNDgyMDA3OTQ2NDA0ZWE0MGVlODg1NTRmMzFiNDEiLCJwIjoiaiJ9)
=> chore: improve unit description in docs

docs-source/source/ts_utils.rst
=> fix: documentation fix

.github/CODEOWNERS
Adding code ownership to charts backend team
=> chore: adding charts team and removing asset-health-services 

PUBLISHING.md
Changed ownership of repo should be visible in read me
=> docs: updating readme

.gemini/config.yaml
Adding gemini config for the repo
=> chore: add initial gemini configuration for code review settings

.github/workflows/code-quality.yaml, .github/workflows/publish.yaml, poetry.lock, pyproject.toml
Dropping support for Python 3.10, which is in the security-fixes-only phase
Numpy 2.3.1, Scipy 1.16, Sphinx-prompt 1.10 etc has dropped support for Python 3.10. In order to align with the data science libraries, we are dropping support for Python 3.10 for Indsl as well. 
Our backend services using Indsl ( Calculations-backend and Skynet ) require Python 3.12, which means that Python 3.10 support can be dropped. This change will be part of a new Indsl release to PyPI.  
unit tests
=> chore: drop support python 3.10 version

docs-source/source/conf.py, poetry.lock, pyproject.toml
Updating sphinx-prompt version to 1.10.0 and removing 1.9.0 which used Python 3.10
Updating the import of the Sphinx extensions to contain underscore
=> chore(deps): update sphinx-prompt to version 1.10.0 

.github/workflows/code-quality.yaml, .github/workflows/publish.yaml, .github/workflows/push-locize.yaml, poetry.lock, pyproject.toml
=> chore: update Python version to 3.13 in configuration files
